cudaError_t gpu_update_grid(unsigned int num_elements,
                     unsigned int *d_lengths,
                     unsigned int dim,
                     Scalar *d_current_val,
                     Scalar *d_grid,
                     Scalar *d_reweighted_grid,
                     Scalar *d_cv_min,
                     Scalar *d_cv_max,
                     Scalar *d_cv_sigma_inv,
                     Scalar scal,
                     Scalar reweight,
                     Scalar W,
                     bool flux_tempered,
                     Scalar T,
                     Scalar *d_histogram,
                     Scalar *d_histogram_plus,
                     unsigned int num_histogram_entries,
                     Scalar ftm_min,
                     Scalar ftm_max); 

cudaError_t gpu_update_histograms(Scalar val,
                                  Scalar cv_min,
                                  Scalar delta,
                                  unsigned int num_points,
                                  Scalar sigma,
                                  bool state,
                                  Scalar *d_histogram,
                                  Scalar *d_histogram_plus);
